/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfessorRouteImport } from './routes/professor'
import { Route as InstituicaoRouteImport } from './routes/instituicao'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as AlunoRouteImport } from './routes/aluno'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfessorIndexRouteImport } from './routes/professor.index'
import { Route as InstituicaoIndexRouteImport } from './routes/instituicao.index'
import { Route as EmpresaIndexRouteImport } from './routes/empresa.index'
import { Route as AlunoIndexRouteImport } from './routes/aluno.index'
import { Route as ProfessorPerfilRouteImport } from './routes/professor.perfil'
import { Route as ProfessorExtratoRouteImport } from './routes/professor.extrato'
import { Route as ProfessorDistribuirRouteImport } from './routes/professor.distribuir'
import { Route as InstituicaoUploadRouteImport } from './routes/instituicao.upload'
import { Route as InstituicaoProfessoresRouteImport } from './routes/instituicao.professores'
import { Route as InstituicaoPerfilRouteImport } from './routes/instituicao.perfil'
import { Route as EmpresaVantagensRouteImport } from './routes/empresa.vantagens'
import { Route as EmpresaResgatesRouteImport } from './routes/empresa.resgates'
import { Route as EmpresaPerfilRouteImport } from './routes/empresa.perfil'
import { Route as AuthRoleRouteImport } from './routes/auth.$role'
import { Route as AlunoVantagensRouteImport } from './routes/aluno.vantagens'
import { Route as AlunoResgatesRouteImport } from './routes/aluno.resgates'
import { Route as AlunoPerfilRouteImport } from './routes/aluno.perfil'
import { Route as AlunoExtratoRouteImport } from './routes/aluno.extrato'

const ProfessorRoute = ProfessorRouteImport.update({
  id: '/professor',
  path: '/professor',
  getParentRoute: () => rootRouteImport,
} as any)
const InstituicaoRoute = InstituicaoRouteImport.update({
  id: '/instituicao',
  path: '/instituicao',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoRoute = AlunoRouteImport.update({
  id: '/aluno',
  path: '/aluno',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorIndexRoute = ProfessorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfessorRoute,
} as any)
const InstituicaoIndexRoute = InstituicaoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InstituicaoRoute,
} as any)
const EmpresaIndexRoute = EmpresaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmpresaRoute,
} as any)
const AlunoIndexRoute = AlunoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlunoRoute,
} as any)
const ProfessorPerfilRoute = ProfessorPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => ProfessorRoute,
} as any)
const ProfessorExtratoRoute = ProfessorExtratoRouteImport.update({
  id: '/extrato',
  path: '/extrato',
  getParentRoute: () => ProfessorRoute,
} as any)
const ProfessorDistribuirRoute = ProfessorDistribuirRouteImport.update({
  id: '/distribuir',
  path: '/distribuir',
  getParentRoute: () => ProfessorRoute,
} as any)
const InstituicaoUploadRoute = InstituicaoUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => InstituicaoRoute,
} as any)
const InstituicaoProfessoresRoute = InstituicaoProfessoresRouteImport.update({
  id: '/professores',
  path: '/professores',
  getParentRoute: () => InstituicaoRoute,
} as any)
const InstituicaoPerfilRoute = InstituicaoPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => InstituicaoRoute,
} as any)
const EmpresaVantagensRoute = EmpresaVantagensRouteImport.update({
  id: '/vantagens',
  path: '/vantagens',
  getParentRoute: () => EmpresaRoute,
} as any)
const EmpresaResgatesRoute = EmpresaResgatesRouteImport.update({
  id: '/resgates',
  path: '/resgates',
  getParentRoute: () => EmpresaRoute,
} as any)
const EmpresaPerfilRoute = EmpresaPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => EmpresaRoute,
} as any)
const AuthRoleRoute = AuthRoleRouteImport.update({
  id: '/auth/$role',
  path: '/auth/$role',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoVantagensRoute = AlunoVantagensRouteImport.update({
  id: '/vantagens',
  path: '/vantagens',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoResgatesRoute = AlunoResgatesRouteImport.update({
  id: '/resgates',
  path: '/resgates',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoPerfilRoute = AlunoPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoExtratoRoute = AlunoExtratoRouteImport.update({
  id: '/extrato',
  path: '/extrato',
  getParentRoute: () => AlunoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aluno': typeof AlunoRouteWithChildren
  '/empresa': typeof EmpresaRouteWithChildren
  '/instituicao': typeof InstituicaoRouteWithChildren
  '/professor': typeof ProfessorRouteWithChildren
  '/aluno/extrato': typeof AlunoExtratoRoute
  '/aluno/perfil': typeof AlunoPerfilRoute
  '/aluno/resgates': typeof AlunoResgatesRoute
  '/aluno/vantagens': typeof AlunoVantagensRoute
  '/auth/$role': typeof AuthRoleRoute
  '/empresa/perfil': typeof EmpresaPerfilRoute
  '/empresa/resgates': typeof EmpresaResgatesRoute
  '/empresa/vantagens': typeof EmpresaVantagensRoute
  '/instituicao/perfil': typeof InstituicaoPerfilRoute
  '/instituicao/professores': typeof InstituicaoProfessoresRoute
  '/instituicao/upload': typeof InstituicaoUploadRoute
  '/professor/distribuir': typeof ProfessorDistribuirRoute
  '/professor/extrato': typeof ProfessorExtratoRoute
  '/professor/perfil': typeof ProfessorPerfilRoute
  '/aluno/': typeof AlunoIndexRoute
  '/empresa/': typeof EmpresaIndexRoute
  '/instituicao/': typeof InstituicaoIndexRoute
  '/professor/': typeof ProfessorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aluno/extrato': typeof AlunoExtratoRoute
  '/aluno/perfil': typeof AlunoPerfilRoute
  '/aluno/resgates': typeof AlunoResgatesRoute
  '/aluno/vantagens': typeof AlunoVantagensRoute
  '/auth/$role': typeof AuthRoleRoute
  '/empresa/perfil': typeof EmpresaPerfilRoute
  '/empresa/resgates': typeof EmpresaResgatesRoute
  '/empresa/vantagens': typeof EmpresaVantagensRoute
  '/instituicao/perfil': typeof InstituicaoPerfilRoute
  '/instituicao/professores': typeof InstituicaoProfessoresRoute
  '/instituicao/upload': typeof InstituicaoUploadRoute
  '/professor/distribuir': typeof ProfessorDistribuirRoute
  '/professor/extrato': typeof ProfessorExtratoRoute
  '/professor/perfil': typeof ProfessorPerfilRoute
  '/aluno': typeof AlunoIndexRoute
  '/empresa': typeof EmpresaIndexRoute
  '/instituicao': typeof InstituicaoIndexRoute
  '/professor': typeof ProfessorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aluno': typeof AlunoRouteWithChildren
  '/empresa': typeof EmpresaRouteWithChildren
  '/instituicao': typeof InstituicaoRouteWithChildren
  '/professor': typeof ProfessorRouteWithChildren
  '/aluno/extrato': typeof AlunoExtratoRoute
  '/aluno/perfil': typeof AlunoPerfilRoute
  '/aluno/resgates': typeof AlunoResgatesRoute
  '/aluno/vantagens': typeof AlunoVantagensRoute
  '/auth/$role': typeof AuthRoleRoute
  '/empresa/perfil': typeof EmpresaPerfilRoute
  '/empresa/resgates': typeof EmpresaResgatesRoute
  '/empresa/vantagens': typeof EmpresaVantagensRoute
  '/instituicao/perfil': typeof InstituicaoPerfilRoute
  '/instituicao/professores': typeof InstituicaoProfessoresRoute
  '/instituicao/upload': typeof InstituicaoUploadRoute
  '/professor/distribuir': typeof ProfessorDistribuirRoute
  '/professor/extrato': typeof ProfessorExtratoRoute
  '/professor/perfil': typeof ProfessorPerfilRoute
  '/aluno/': typeof AlunoIndexRoute
  '/empresa/': typeof EmpresaIndexRoute
  '/instituicao/': typeof InstituicaoIndexRoute
  '/professor/': typeof ProfessorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aluno'
    | '/empresa'
    | '/instituicao'
    | '/professor'
    | '/aluno/extrato'
    | '/aluno/perfil'
    | '/aluno/resgates'
    | '/aluno/vantagens'
    | '/auth/$role'
    | '/empresa/perfil'
    | '/empresa/resgates'
    | '/empresa/vantagens'
    | '/instituicao/perfil'
    | '/instituicao/professores'
    | '/instituicao/upload'
    | '/professor/distribuir'
    | '/professor/extrato'
    | '/professor/perfil'
    | '/aluno/'
    | '/empresa/'
    | '/instituicao/'
    | '/professor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aluno/extrato'
    | '/aluno/perfil'
    | '/aluno/resgates'
    | '/aluno/vantagens'
    | '/auth/$role'
    | '/empresa/perfil'
    | '/empresa/resgates'
    | '/empresa/vantagens'
    | '/instituicao/perfil'
    | '/instituicao/professores'
    | '/instituicao/upload'
    | '/professor/distribuir'
    | '/professor/extrato'
    | '/professor/perfil'
    | '/aluno'
    | '/empresa'
    | '/instituicao'
    | '/professor'
  id:
    | '__root__'
    | '/'
    | '/aluno'
    | '/empresa'
    | '/instituicao'
    | '/professor'
    | '/aluno/extrato'
    | '/aluno/perfil'
    | '/aluno/resgates'
    | '/aluno/vantagens'
    | '/auth/$role'
    | '/empresa/perfil'
    | '/empresa/resgates'
    | '/empresa/vantagens'
    | '/instituicao/perfil'
    | '/instituicao/professores'
    | '/instituicao/upload'
    | '/professor/distribuir'
    | '/professor/extrato'
    | '/professor/perfil'
    | '/aluno/'
    | '/empresa/'
    | '/instituicao/'
    | '/professor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlunoRoute: typeof AlunoRouteWithChildren
  EmpresaRoute: typeof EmpresaRouteWithChildren
  InstituicaoRoute: typeof InstituicaoRouteWithChildren
  ProfessorRoute: typeof ProfessorRouteWithChildren
  AuthRoleRoute: typeof AuthRoleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/professor': {
      id: '/professor'
      path: '/professor'
      fullPath: '/professor'
      preLoaderRoute: typeof ProfessorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instituicao': {
      id: '/instituicao'
      path: '/instituicao'
      fullPath: '/instituicao'
      preLoaderRoute: typeof InstituicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno': {
      id: '/aluno'
      path: '/aluno'
      fullPath: '/aluno'
      preLoaderRoute: typeof AlunoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor/': {
      id: '/professor/'
      path: '/'
      fullPath: '/professor/'
      preLoaderRoute: typeof ProfessorIndexRouteImport
      parentRoute: typeof ProfessorRoute
    }
    '/instituicao/': {
      id: '/instituicao/'
      path: '/'
      fullPath: '/instituicao/'
      preLoaderRoute: typeof InstituicaoIndexRouteImport
      parentRoute: typeof InstituicaoRoute
    }
    '/empresa/': {
      id: '/empresa/'
      path: '/'
      fullPath: '/empresa/'
      preLoaderRoute: typeof EmpresaIndexRouteImport
      parentRoute: typeof EmpresaRoute
    }
    '/aluno/': {
      id: '/aluno/'
      path: '/'
      fullPath: '/aluno/'
      preLoaderRoute: typeof AlunoIndexRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/professor/perfil': {
      id: '/professor/perfil'
      path: '/perfil'
      fullPath: '/professor/perfil'
      preLoaderRoute: typeof ProfessorPerfilRouteImport
      parentRoute: typeof ProfessorRoute
    }
    '/professor/extrato': {
      id: '/professor/extrato'
      path: '/extrato'
      fullPath: '/professor/extrato'
      preLoaderRoute: typeof ProfessorExtratoRouteImport
      parentRoute: typeof ProfessorRoute
    }
    '/professor/distribuir': {
      id: '/professor/distribuir'
      path: '/distribuir'
      fullPath: '/professor/distribuir'
      preLoaderRoute: typeof ProfessorDistribuirRouteImport
      parentRoute: typeof ProfessorRoute
    }
    '/instituicao/upload': {
      id: '/instituicao/upload'
      path: '/upload'
      fullPath: '/instituicao/upload'
      preLoaderRoute: typeof InstituicaoUploadRouteImport
      parentRoute: typeof InstituicaoRoute
    }
    '/instituicao/professores': {
      id: '/instituicao/professores'
      path: '/professores'
      fullPath: '/instituicao/professores'
      preLoaderRoute: typeof InstituicaoProfessoresRouteImport
      parentRoute: typeof InstituicaoRoute
    }
    '/instituicao/perfil': {
      id: '/instituicao/perfil'
      path: '/perfil'
      fullPath: '/instituicao/perfil'
      preLoaderRoute: typeof InstituicaoPerfilRouteImport
      parentRoute: typeof InstituicaoRoute
    }
    '/empresa/vantagens': {
      id: '/empresa/vantagens'
      path: '/vantagens'
      fullPath: '/empresa/vantagens'
      preLoaderRoute: typeof EmpresaVantagensRouteImport
      parentRoute: typeof EmpresaRoute
    }
    '/empresa/resgates': {
      id: '/empresa/resgates'
      path: '/resgates'
      fullPath: '/empresa/resgates'
      preLoaderRoute: typeof EmpresaResgatesRouteImport
      parentRoute: typeof EmpresaRoute
    }
    '/empresa/perfil': {
      id: '/empresa/perfil'
      path: '/perfil'
      fullPath: '/empresa/perfil'
      preLoaderRoute: typeof EmpresaPerfilRouteImport
      parentRoute: typeof EmpresaRoute
    }
    '/auth/$role': {
      id: '/auth/$role'
      path: '/auth/$role'
      fullPath: '/auth/$role'
      preLoaderRoute: typeof AuthRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/vantagens': {
      id: '/aluno/vantagens'
      path: '/vantagens'
      fullPath: '/aluno/vantagens'
      preLoaderRoute: typeof AlunoVantagensRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/resgates': {
      id: '/aluno/resgates'
      path: '/resgates'
      fullPath: '/aluno/resgates'
      preLoaderRoute: typeof AlunoResgatesRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/perfil': {
      id: '/aluno/perfil'
      path: '/perfil'
      fullPath: '/aluno/perfil'
      preLoaderRoute: typeof AlunoPerfilRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/extrato': {
      id: '/aluno/extrato'
      path: '/extrato'
      fullPath: '/aluno/extrato'
      preLoaderRoute: typeof AlunoExtratoRouteImport
      parentRoute: typeof AlunoRoute
    }
  }
}

interface AlunoRouteChildren {
  AlunoExtratoRoute: typeof AlunoExtratoRoute
  AlunoPerfilRoute: typeof AlunoPerfilRoute
  AlunoResgatesRoute: typeof AlunoResgatesRoute
  AlunoVantagensRoute: typeof AlunoVantagensRoute
  AlunoIndexRoute: typeof AlunoIndexRoute
}

const AlunoRouteChildren: AlunoRouteChildren = {
  AlunoExtratoRoute: AlunoExtratoRoute,
  AlunoPerfilRoute: AlunoPerfilRoute,
  AlunoResgatesRoute: AlunoResgatesRoute,
  AlunoVantagensRoute: AlunoVantagensRoute,
  AlunoIndexRoute: AlunoIndexRoute,
}

const AlunoRouteWithChildren = AlunoRoute._addFileChildren(AlunoRouteChildren)

interface EmpresaRouteChildren {
  EmpresaPerfilRoute: typeof EmpresaPerfilRoute
  EmpresaResgatesRoute: typeof EmpresaResgatesRoute
  EmpresaVantagensRoute: typeof EmpresaVantagensRoute
  EmpresaIndexRoute: typeof EmpresaIndexRoute
}

const EmpresaRouteChildren: EmpresaRouteChildren = {
  EmpresaPerfilRoute: EmpresaPerfilRoute,
  EmpresaResgatesRoute: EmpresaResgatesRoute,
  EmpresaVantagensRoute: EmpresaVantagensRoute,
  EmpresaIndexRoute: EmpresaIndexRoute,
}

const EmpresaRouteWithChildren =
  EmpresaRoute._addFileChildren(EmpresaRouteChildren)

interface InstituicaoRouteChildren {
  InstituicaoPerfilRoute: typeof InstituicaoPerfilRoute
  InstituicaoProfessoresRoute: typeof InstituicaoProfessoresRoute
  InstituicaoUploadRoute: typeof InstituicaoUploadRoute
  InstituicaoIndexRoute: typeof InstituicaoIndexRoute
}

const InstituicaoRouteChildren: InstituicaoRouteChildren = {
  InstituicaoPerfilRoute: InstituicaoPerfilRoute,
  InstituicaoProfessoresRoute: InstituicaoProfessoresRoute,
  InstituicaoUploadRoute: InstituicaoUploadRoute,
  InstituicaoIndexRoute: InstituicaoIndexRoute,
}

const InstituicaoRouteWithChildren = InstituicaoRoute._addFileChildren(
  InstituicaoRouteChildren,
)

interface ProfessorRouteChildren {
  ProfessorDistribuirRoute: typeof ProfessorDistribuirRoute
  ProfessorExtratoRoute: typeof ProfessorExtratoRoute
  ProfessorPerfilRoute: typeof ProfessorPerfilRoute
  ProfessorIndexRoute: typeof ProfessorIndexRoute
}

const ProfessorRouteChildren: ProfessorRouteChildren = {
  ProfessorDistribuirRoute: ProfessorDistribuirRoute,
  ProfessorExtratoRoute: ProfessorExtratoRoute,
  ProfessorPerfilRoute: ProfessorPerfilRoute,
  ProfessorIndexRoute: ProfessorIndexRoute,
}

const ProfessorRouteWithChildren = ProfessorRoute._addFileChildren(
  ProfessorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlunoRoute: AlunoRouteWithChildren,
  EmpresaRoute: EmpresaRouteWithChildren,
  InstituicaoRoute: InstituicaoRouteWithChildren,
  ProfessorRoute: ProfessorRouteWithChildren,
  AuthRoleRoute: AuthRoleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
