spring.application.name=moeda

# Conexao com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/braincoins
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:admin2513}
spring.datasource.driver-class-name=org.postgresql.Driver

#Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Upload de arquivos
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB