spring.application.name=moeda

# Conexao com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/braincoins
spring.datasource.username=postgres
spring.datasource.password=admin2513
spring.datasource.driver-class-name=org.postgresql.Driver

#Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update