@startuml diagrama-componentes-implantacao
!define SPRITESURL https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/v1.1/sprites
!define IMAGESSURL https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/v1.1/pngs

skinparam node {
    BackgroundColor #F5F5F5
    BorderColor #555555
    FontStyle bold
}

skinparam component {
    BackgroundColor #e8f4ff
    BorderColor #336699
}

skinparam database {
    BackgroundColor #FFF5CC
    BorderColor #AA8800
}

node "Dispositivo do Usuário" as UserDevice {
    node "Navegador Web" as UserBrowser {
        component "<img:IMAGESSURL/create-react-app.png>\nAplicação Front-End\nReact + Vite + TypeScript\nHospedado em nuvem (Vercel)" as Frontend
    }
}

node "Servidor da Aplicação\nHospedado em nuvem (Render)\n<img:IMAGESSURL/docker.png>" as ApplicationServer {
    component "<img:IMAGESSURL/java.png>\nAPI REST BrainCoins\nJava Spring Boot" as restApi
    component "<img:IMAGESSURL/java.png>\nautenticação\nJava Spring Boot" as AuthService
    component "<img:IMAGESSURL/java.png>\nalunos\nJava Spring Boot" as AlunoService
    component "<img:IMAGESSURL/java.png>\nemail\nJava Spring Boot" as EmailService
    component "<img:IMAGESSURL/java.png>\nempresas\nJava Spring Boot" as EmpresaService
    component "<img:IMAGESSURL/java.png>\nfile storage\nJava Spring Boot" as FileStorage
    component "<img:IMAGESSURL/java.png>\ninstituicoes\nJava Spring Boot" as InstituicaoService
    component "<img:IMAGESSURL/java.png>\nprofessores\nJava Spring Boot" as ProfessorService
    component "<img:IMAGESSURL/java.png>\nresgate\nJava Spring Boot" as ResgateService
    component "<img:IMAGESSURL/java.png>\ntransacoes\nJava Spring Boot" as TransacaoService
    component "<img:IMAGESSURL/java.png>\ntrocas\nJava Spring Boot" as TrocasService
    queue "<img:IMAGESSURL/rabbitmq.png>\nFila de Trocas\nRabbitMQ" as TrocasQueue
    component "<img:IMAGESSURL/java.png>\nvantagens\nJava Spring Boot" as VantagemService

    interface "REST" as REST_auth
    interface "REST" as REST_alunos
    interface "REST" as REST_email
    interface "REST" as REST_empresas
    interface "REST" as REST_storage
    interface "REST" as REST_instituicoes
    interface "REST" as REST_professores
    interface "REST" as REST_resgate
    interface "REST" as REST_transacoes
    interface "REST" as REST_trocas
    interface "REST" as REST_trocas_queue
    interface "REST" as REST_vantagens
}
interface "HTTP" as HTTP_api

node "<img:IMAGESSURL/neon.png>\nNuvem (Neon)" as NeonCloud {
    database "<img:IMAGESSURL/postgresql.png>\nBanco de Dados\nPostgreSQL" as DB
}
interface "TCP/IP" as TCP_banco

Frontend -down-( HTTP_api
restApi -up- HTTP_api

AuthService -up- REST_auth
restApi -down-( REST_auth
AlunoService -up- REST_alunos
restApi -down-( REST_alunos
EmailService -up- REST_email
restApi -down-( REST_email
EmpresaService -up- REST_empresas
restApi -down-( REST_empresas
FileStorage -up- REST_storage
restApi -down-( REST_storage
InstituicaoService -up- REST_instituicoes
restApi -down-( REST_instituicoes
ProfessorService -up- REST_professores
restApi -down-( REST_professores
ResgateService -up- REST_resgate
restApi -down-( REST_resgate
TransacaoService -up- REST_transacoes
restApi -down-( REST_transacoes
TrocasService -up- REST_trocas
restApi -down-( REST_trocas
TrocasService -left- REST_trocas_queue
TrocasQueue -down-( REST_trocas_queue
VantagemService -up- REST_vantagens
restApi -down-( REST_vantagens

DB -up- TCP_banco
AuthService -down-( TCP_banco
AlunoService -down-( TCP_banco
EmailService -down-( TCP_banco
EmpresaService -down-( TCP_banco
FileStorage -down-( TCP_banco
InstituicaoService -down-( TCP_banco
ProfessorService -down-( TCP_banco
ResgateService -down-( TCP_banco
TransacaoService -down-( TCP_banco
VantagemService -down-( TCP_banco
TrocasService -down-( TCP_banco

@enduml