services:
  postgres:
    image: postgres:18
    container_name: braincoins-db
    environment:
      POSTGRES_DB: braincoins
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - braincoins_data:/var/lib/postgresql

volumes:
  braincoins_data: